Feature/login flow
fahademali/todo-assignment pull request #5
Opened 2023-10-25 14:43 UTC by fahademali

2023-10-31 09:30 UTC, mvaleed requested changes

2023-10-31 09:30 UTC, mvaleed commented on user_service/middlewares/middlewares.go
> +	token := strings.Split(ctx.Request.Header["Authorization"][0], " ")[1]
The code will break if:
1. No authorization head is passed in headers.
2. Authorization header is passed, but the value is not space separated.

2023-10-31 09:30 UTC, mvaleed commented on user_service/middlewares/middlewares.go
> +	if user.Role != "admin" {
'admin' string should be a constant.
```
UserRoleAdmin = "admin"
```

2023-10-31 09:30 UTC, mvaleed commented on user_service/models/user.go
> +	Nbf        float64 `json:"nbf"`
Whats nbf?

2023-10-31 09:30 UTC, mvaleed commented on user_service/repo/user.go
> +	SetAdminRole(email string) error
UpdateUserByEmail already does this, no?

2023-10-31 09:30 UTC, mvaleed commented on user_service/services/token_service.go
> +		}, nil
Avoid unnecessary nested if.
Can be avoided by:
```
claims, ok := token.Claims.(jwt.MapClaims)
If !ok or !token.Valid { return err }
```

2023-10-31 09:30 UTC, mvaleed commented on user_service/middlewares/middlewares.go
> +	if user.Role != "admin" {
.

2023-10-31 09:30 UTC, mvaleed commented on user_service/middlewares/middlewares.go
> +	log.GetLog().Info(user)
h

2023-10-31 14:26 UTC, fahademali commented on todo_service/apis/handlers/list.go
> +	HandleUpdateListName(ctx *gin.Context)
"Name" not required.

2023-10-31 14:27 UTC, fahademali commented on todo_service/apis/handlers/list.go
> +	listID := ctx.Param("listID")
make listID snake case

2023-10-31 14:27 UTC, fahademali commented on todo_service/apis/handlers/list.go
> +	if err := lh.listService.UpdateList(listID, requestBody.Name); err != nil {
send complete request body

2023-10-31 14:29 UTC, fahademali commented on todo_service/apis/handlers/todo.go
> +	listID := ctx.Param(":listID")
make listID snakecase

2023-10-31 14:33 UTC, fahademali commented on todo_service/apis/handlers/todo.go
> +	if err := th.todoService.DeleteTodo(todoID); err != nil {
make it secured

2023-10-31 14:35 UTC, fahademali commented on todo_service/apis/handlers/todo.go
> +	todoID := ctx.Param("id")
keep it consistent with the struct types

2023-10-31 14:35 UTC, fahademali commented on todo_service/apis/handlers/todo.go
> +	todo, err := th.todoService.GetTodo(todoID)
make it secure.

2023-10-31 14:36 UTC, fahademali commented on todo_service/apis/routes/todo_service.go
> +	tr.DELETE("/todos/:id", todoHandlers.HandleDeleteTodo)
append list/listid on the route.

2023-10-31 14:47 UTC, fahademali commented on todo_service/repo/list.go
> +func (lr *ListRepo) Update(id string, name string) error {
send struct as argument

2023-10-31 14:51 UTC, fahademali commented on todo_service/services/todo.go
> +func (ts *TodoService) GetTodo(id string) (models.Todo, error) {
clean

2023-10-31 14:56 UTC, fahademali commented on todo_service/services/todo.go
> +func (ts *TodoService) UpdateTodo(id string, todoUpdates models.UpdateTodoRequest) error {
make it patch, dont make it put.

2023-10-31 14:57 UTC, fahademali commented on user_service/apis/handlers/user.go
> -		"data": "/getprofile Not Implemented yet",
implement this.

2023-11-06 09:17 UTC, mvaleed approved these changes

2023-11-06 09:17 UTC, merged